name: ash_test
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - pip
  - openmm
  - pdbfixer
  - mdtraj
  - numpy
  - scipy
  - matplotlib
  - parmed
  - plumed
  - mdanalysis
  - ase
  - xtb
  - xtb-python
  - typing_extensions
  - pip:
      - geometric
      - pyscf
      - pyframe
