name: ash
channels:
  - conda-forge
dependencies:
  - python>=3.13
  - pip
  - mdtraj
  - numpy
  - scipy
  - matplotlib
  - parmed
  - openmm
  - openmmtools
  - pdbfixer
  - openmm-plumed
  - openff-toolkit
  - openmmforcefields
  - ase
  - xtb
  - xtb-python
  - geometric
  - pyscf
  - pytest
  - pip:
      - pyframe
